CapaPresentacionTienda/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaEntidad.Paypal;
using CapaNegocio;
using System.IO;
using CapaPresentacionTienda.Filter;
using System.ComponentModel;
using System.Collections;
using System.Threading.Tasks;
using System.Data;
using System.Globalization;

namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }
        [ValidarSession]
        [Authorize]
        public ActionResult Carrito()
        {
            return View();
        }

        #region DETALLE DEL PRODUCTO
        public ActionResult DetalleProducto(string idproducto = " ")
        {

            Producto oProducto = new Producto();
            bool conversion;

            oProducto = new CN_Producto().Listar().Where(p => p.id_prod == idproducto).FirstOrDefault();

            if (oProducto != null)
            {
                oProducto.Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oProducto.rutafoto, oProducto.foto), out conversion);
                oProducto.extension = Path.GetExtension(oProducto.foto);
            }

            return View(oProducto);
        }

        #endregion

        #region CATEGORIAS
        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> lista = new List<Categoria>();

            lista = new CN_Categoria().Listar().Select(c => new Categoria()
            {
                id_categoria = c.id_categoria,
                nombre_categoria = c.nombre_categoria,
                estado = c.estado
            }).Where(c =>
                 c.estado == "HABILITADO  "
           ).ToList();

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region PINTAR PRODUCTOS
        [HttpPost]
        public JsonResult ListarProducto(string idcategoria)
        {
            List<Producto> lista = new List<Producto>();

            bool conversion;

            lista = new CN_Producto().Listar().Select(p => new Producto()
            {
                id_prod = p.id_prod,
                nombre = p.nombre,
                descripcion = p.descripcion,
                oCategoria = p.oCategoria,
                oCatalogo = p.oCatalogo,
                precio = p.precio,
                stock = p.stock,
                rutafoto = p.rutafoto,
                Base64 = CN_Recursos.ConvertirBase64(Path.Combine(p.rutafoto, p.foto), out conversion),
                extension = Path.GetExtension(p.foto),
                estado = p.estado
            }).Where(p =>
                p.oCategoria.id_categoria == (idcategoria == " " ? p.oCategoria.id_categoria : idcategoria) &&
                p.stock > 0 && p.estado == "HABILITADO  "
            ).ToList();

            var jsonresult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;

            return jsonresult;

        }
        #endregion

        #region LOGICA CARRITO     

        [HttpPost]
        public JsonResult AgregarCarrito(string idproducto)
        {
            string idclienteU = ((Usuario_Admin)Session["USUARIO"]).OclienteUser.id_clienteU;

            bool existe = new CN_Carrito().ExisteCarrito(idclienteU, idproducto);

            bool respuesta = false;

            string mensaje = string.Empty;

            if (existe)
            {
                mensaje = "El producto ya existe en el carrito";
            }
            else
            {
                respuesta = new CN_Carrito().operacionCarrito(idclienteU, idproducto, true, out mensaje);
            }

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult CantidadCarrito()
        {
            string idclienteU = ((Usuario_Admin)Session["USUARIO"]).OclienteUser.id_clienteU;
            int cantidad = new CN_Carrito().CantidadEnCarrito(idclienteU);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult ListarProductoCarrito()
        {

            string idclienteU = ((Usuario_Admin)Session["USUARIO"]).OclienteUser.id_clienteU;
            List<Carrito> olista = new List<Carrito>();
            bool conversion;


            olista = new CN_Carrito().ListarProducto(idclienteU).Select(oc => new Carrito()
            {
                oProducto = new Producto()
                {
                    id_prod = oc.oProducto.id_prod,
                    nombre = oc.oProducto.nombre,
                    precio = oc.oProducto.precio,
                    descripcion = oc.oProducto.descripcion,
                    rutafoto = oc.oProducto.rutafoto,
                    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oc.oProducto.rutafoto, oc.oProducto.foto), out conversion),
                    extension = Path.GetExtension(oc.oProducto.foto)
                },
                Cantidad = oc.Cantidad,
            }).ToList();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult OperacionCarrito(string idproducto, bool sumar)
        {
            string idclienteU = ((Usuario_Admin)Session["USUARIO"]).OclienteUser.id_clienteU;
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Carrito().operacionCarrito(idclienteU, idproducto, sumar, out mensaje);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCarrito(string idproducto)
        {
            string idclienteU = ((Usuario_Admin)Session["USUARIO"]).OclienteUser.id_clienteU;
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Carrito().EliminarCarrito(idclienteU, idproducto);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerDepartamento()
        {
            List<Departamento> oLista = new List<Departamento>();

            oLista = new CN_Ubicacion().ObtenerDepartamento();
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        public JsonResult ObtenerMunicipio(string IdDepartamento)
        {
            List<Municipio> oLista = new List<Municipio>();

            oLista = new CN_Ubicacion().ObtenerMunicipio(IdDepartamento);
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);


        }

        #endregion

        #region Logica VentaTransac

        [HttpPost]
        public async Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, VentaTransac oVentaTransac)
        {
            decimal total = 0;
            DataTable detalle_venta = new DataTable();
            detalle_venta.Locale = new CultureInfo("es-NI");
            detalle_venta.Columns.Add("IdProducto", typeof(string));
            detalle_venta.Columns.Add("Cantidad", typeof(int));
            detalle_venta.Columns.Add("Total", typeof(decimal));

            List<Item> oListaItem = new List<Item>();

            foreach(Carrito oCarrito in oListaCarrito)
            {
                decimal subTotal = Convert.ToDecimal(oCarrito.Cantidad.ToString()) * oCarrito.oProducto.precio;
                total += subTotal;

                //oListaItem.Add(new Item(){
                //    name = oCarrito.oProducto.nombre,
                //    quantity = oCarrito.Cantidad.ToString(),
                //    unit_amount = new UnitAmount()
                //    {
                //        currency_code = "USD",
                //        value = oCarrito.oProducto.precio.ToString("G",new CultureInfo("es-NI"))
                //    } 

                //});

                detalle_venta.Rows.Add(new object[]{
                    oCarrito.oProducto.id_prod,
                    oCarrito.Cantidad,
                    subTotal
                });
            }

            total = (total + (total * ((decimal)(0.15))));//aplicamos iva
            total = decimal.Round(total, 2);

            PurchaseUnit purchaseUnit = new PurchaseUnit()
            {
                amount = new Amount()
                {
                    currency_code = "USD",
                    value = total.ToString("G", new CultureInfo("es-NI")),
                    breakdown = new Breakdown()
                    {
                        item_total = new ItemTotal()
                        {
                            currency_code = "USD",
                            value = total.ToString("G", new CultureInfo("es-NI"))
                        }
                    }
                   
                },
                description = "compra de articulo de mi tienda"
            };

            Checkout_Order oCheckoutOrder = new Checkout_Order()
            {
                intent = "CAPTURE",
                purchase_units = new List<PurchaseUnit>() { purchaseUnit },
                application_context = new ApplicationContext()
                {
                    brand_name = "PedidosFerre.com",
                    landing_page = "NO_PREFERENCE",
                    user_action = "PAY_NOW",
                    return_url = "https://localhost:44343/Tienda/PagoEfectuado",
                    cancel_url = "https://localhost:44343/Tienda/Carrito"
                }

            };

           
            oVentaTransac.MontoTotal = total;
            oVentaTransac.id_clienteU = ((Usuario_Admin)Session["USUARIO"]).OclienteUser.id_clienteU;

            TempData["VentaTransac"] = oVentaTransac;

CapaPresentacionTienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi tienda online</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid px-4">
            <a class="navbar-brand"><img src="~/Content/images/logo2.2.png" width="200" height="70"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class=" collapse navbar-collapse" id="navbarSupportedContent" style="width:50%">
            <ul class="navbar-nav mb-2 me-auto mb-lg-0 ms-lg-4 w-75">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Tienda")">Inicio</a></li>
                @*buscador*@
                <li class="nav-item w-100" id="buscador" hidden>

                        <div class="height d-flex justify-content-center align-items-center flex-grow-1">
                            <div class="col-md-9">
                                <div class="search d-flex justify-content-center align-items-center gap-xl-3">
                                    <i class="fa fa-search"></i>
                                    <input type="text" class="form-control" placeholder="Buscas algo especifico?" id="producto_especifico">
                                    <button class="btn btn-primary" id="btn_prod_espe">Search</button>
                                </div>

                            </div>

                        </div>
                    
                </li>
                
            </ul>
            <form class="d-flex gap-xl-4">

                @if (Session["USUARIO"] == null)
                {
                    <a class="btn btn-outline-dark" aria-current="page" href="@Url.Action("Index", "Acceso")"><i class="fas fa-sign-out-alt me-1"></i>Iniciar Sesion</a>

                }
                else
                {


                    @*<a id="btnpendiente" class="btn btn-outline-dark" style="margin-right:10px" href="@Url.Action("Pendientes","Tienda")">
                        <i class="fas fa-truck-loading me-1"></i>
                        Pendientes

                    </a>*@

                    <a id="btncarrito" class="btn btn-outline-dark" href="@Url.Action("Carrito", "Tienda")">
                        <i class="fas fa-shopping-cart me-1"></i>
                        Carrito
                        <span class="badge bg-dark text-white ms-1 rounded-pill" id="cantidadcarrito">0</span>
                    </a>

                    <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                                <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                                <li><a class="dropdown-item" href="@Url.Action("MisCompras","Tienda")">Mis compras</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="@Url.Action("CerrarSesion", "Acceso")">Cerrar Sesion</a></li>
                            </ul>
                        </li>
                    </ul>
                }
            </form>
        </div>
        </div>
    </nav>
    <!-- Header-->
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

<script>

    $(document).ready(function () {

        MostrarCantidadCarrito();

    })
        function MostrarCantidadCarrito() {

            if ($("#cantidadcarrito").length > 0) {

                jQuery.ajax({

                    url: '@Url.Action("CantidadCarrito", "Tienda")',
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=uf-8",
                    success: function (data) {

                        $("#cantidadcarrito").text(data.cantidad)
                    }

                });


            }

        }

</script>


</body>
</html>