CapaPresentacionAdmin/Controllers/MantenedorController.cs
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaPresentacionAdmin.Permisos;
using Microsoft.Ajax.Utilities;
using WebGrease.Css.Extensions;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]
    public class MantenedorController : Controller
    {

        // GET: Mantenedor
        [PermisosRol(4)]
        public ActionResult Productos()
        {
            return View();
        }

        [PermisosRol(5)]
        public ActionResult Categoria()
        {
            return View();
        }

        [PermisosRol(6)]
        public ActionResult Roles()
        {
            return View();
        }


        #region PRODUCTO

        [HttpGet/*,PermisosRol(CapaEntidad.Rol.General)*/]
        public JsonResult ListarProducto()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = new CN_Producto().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProducto(String objeto, HttpPostedFileBase archivoImagen)
        {

            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool Guardar_imagen_exito = true;

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(objeto);

            decimal precio, costo;


            if (decimal.TryParse(oProducto.precioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-NI"), out precio))
            {
                oProducto.precio = precio;
            }
            else
            {
                return Json(new { operacion_exitosa = false, mensaje = "Error con el formato de precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }

            if (decimal.TryParse(oProducto.costoTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-NI"), out costo))
            {
                oProducto.costo = costo;
            }
            else
            {
                return Json(new { operacion_exitosa = false, mensaje = "Error con el formato de costo debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }



            if (oProducto.id_prod == string.Empty)
            {

                string idproducto = new CN_Producto().Registrar(oProducto, out mensaje);
                if (idproducto != string.Empty)
                {
                    oProducto.id_prod = idproducto;
                }
                else
                {
                    operacion_exitosa = false;
                }
            }
            else
            {
                operacion_exitosa = new CN_Producto().Editar(oProducto, out mensaje);
            }


            if (operacion_exitosa)
            {
                if (archivoImagen != null)
                {
                    string ruta_guardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(archivoImagen.FileName);
                    string nombre_imagen = string.Concat(oProducto.id_prod.ToString(), extension);

                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(ruta_guardar, nombre_imagen));
                    }
                    catch (Exception ex)
                    {
                        mensaje = ex.Message;
                        Guardar_imagen_exito = false;
                    }

                    if (Guardar_imagen_exito)
                    {
                        oProducto.rutafoto = ruta_guardar;
                        oProducto.foto = nombre_imagen;
                        bool rspta = new CN_Producto().GuardarDatosImagen(oProducto, out mensaje);
                    }
                    else
                    {
                        mensaje = "Producto guardado pero hubo error con la imagen";
                    }
                }
            }

            return Json(new { operacionExitosa = operacion_exitosa, idproducto = oProducto.id_prod, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        //unimos el nombre de la foto y la ruta y la convertimos a texto base64 para pintarla
        [HttpPost]
        public JsonResult ImagenProducto(String id)
        {
            bool conversion;
            Producto oProducto = new CN_Producto().Listar().Where(P => P.id_prod == id).FirstOrDefault();

            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine(oProducto.rutafoto, oProducto.foto), out conversion);

            return Json(new
            {

                conversion = conversion,
                textoBase64 = textoBase64,
                extension = Path.GetExtension(oProducto.foto)

            },
                JsonRequestBehavior.AllowGet
            );
        }

        [HttpPost]

        public JsonResult EliminarProducto(string id)
        {
            bool resultado = false;
            resultado = new CN_Producto().Eliminar(id);
            return Json(new { resultado }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region CATEGORIA

        [HttpGet/*,PermisosRol(CapaEntidad.Rol.General)*/]
        public JsonResult ListarCategoria()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = new CN_Categoria().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(String objeto)
        {

            //bool resEditar = false;
            string mensaje = string.Empty;
            bool salida = true;

            Categoria ocategoria = new Categoria();
            ocategoria = JsonConvert.DeserializeObject<Categoria>(objeto);

            if (ocategoria.id_categoria == "")
            {
                string idcat = new CN_Categoria().Registrar(ocategoria, out mensaje);
                
                if (idcat != string.Empty)
                {
                    ocategoria.id_categoria = idcat;
                }
                else
                {
                    salida = false;
                }
            }
            else
            {
                salida = new CN_Categoria().Editar(ocategoria, out mensaje);
            }

            return Json(new { salida = salida, idcat = ocategoria.id_categoria, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

           
        }

        [HttpPost]
        public JsonResult EliminarCategoria(string id)
        {
            bool resultado = false;
            resultado = new CN_Categoria().Eliminar(id);
            return Json(new { resultado = resultado }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Roles
        [HttpGet]
        public JsonResult ListarRoles()
        {
            List<Rol> oLista = new List<Rol>();
            oLista = new CN_Rol().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ListarModulosPorRol()
        {
           
            //string rolAdmin = ((Usuario_Admin)Session["ADMIN"]).ORol.IdRol;
            List<RolPorModulo> oLista = new List<RolPorModulo>();
            oLista = new CN_Rol().ListarRolPorModulo();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarRol(string rol,int idu,int idv,int idc,int idp)
        {
            string mensaje = string.Empty;
            bool salida = false;

            
                salida = new CN_Rol().RegistrarRol(rol,idu,idv, idc, idp, out mensaje);
            return Json(new { salida = salida,  mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult eliminarRol(string idRol)
        {
            string mensaje = string.Empty;
            bool resultado = false;

            resultado = new CN_Rol().eliminarRol(idRol, out mensaje);
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region CATALOGO
        [HttpGet/*,PermisosRol(CapaEntidad.Rol.General)*/]
        public JsonResult ListarCatalogo()
        {
            List<Catalogo> oLista = new List<Catalogo>();
            oLista = new CN_Catalogo().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

CapaPresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MI FERRETERIA</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
@Scripts.Render("~/bundles/jquery")
<body class="sb-nav-fixed">

    <script>

           jQuery.ajax({
            url: '@Url.Action("ListarModulosPorRol", "Mantenedor")',
            type: "GET",
            data:null,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
               success: function (data) {
                   //guardamos todos los modulos y los iconos de cada modulo
                   let modulos = document.querySelectorAll("#modulo")
                   let iconosModulo = document.querySelectorAll("#denegado")

                   data.data.forEach((data, indexData) => {
                       if (!data.Estado) {
                           modulos[indexData].removeAttribute("href")
                           iconosModulo[indexData].setAttribute("class", "fas fa-lock")
                           iconosModulo[indexData].style.marginLeft = "10px"
                       }
                   })
            },
            error: function (error) {
                console.log(error)
            }
           })

    </script>
    @if (Session["ADMIN"] != null)
    {

        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3 mt-2">
                <img src="~/Content/images/logoAdm2.2.png" width="160" height="60" />
            </a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            @*@ <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                        <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </form>*@
            <!-- Navbar-->


            <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="@Url.Action("CerrarSesion", "Acceso")">Cerrar Sesion</a></li>
                    </ul>
                </li>
            </ul>

        </nav><div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading mt-4">RESUMEN</div>

                            <a class="nav-link" href="@Url.Action("Index", "Home")" id="modulo">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard <i id="denegado"></i>
                            </a>


                            <a class="nav-link" href="@Url.Action("Usuarios", "Home")" id="modulo">
                                <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                                Usuarios <i id="denegado"></i>
                            </a>


                            <a class="nav-link" href="@Url.Action("Ventas", "Home")" id="modulo">
                                <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                                Ventas <i id="denegado"></i>
                            </a>





                            @*MANTENIMEINTO*@


                            <div class="sb-sidenav-menu-heading">MANTENIMIENTO</div>

                            <a class="nav-link" href="@Url.Action("Productos", "Mantenedor")" id="modulo">
                                <div class="sb-nav-link-icon"><i class="fas fa-box-open"></i></div>
                                Productos <i id="denegado"></i>
                            </a>
                            <a class="nav-link" href="@Url.Action("Categoria", "Mantenedor")" id="modulo">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Categorias <i id="denegado"></i>
                            </a>

                            <a class="nav-link" href="@Url.Action("Roles", "Mantenedor")" id="modulo">
                                <div class="sb-nav-link-icon"><i class="fa fa-users"></i></div>
                                Roles <i id="denegado"></i>
                            </a>

                        </div>
                    </div>

                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>

                    <div class="container-fluid px-4">

                        @RenderBody()

                    </div>

                </main>

            </div>
        </div>
    }
    else
    {
        <a class="nav-link" href="@Url.Action("Acceso", "Index")">

        </a>

    }
    @*@ @RenderBody()
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@

    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>